#!/usr/bin/env python
'''
boatdctl - boatd control

Usage:
    boatdctl info
    boatdctl stop
    boatdctl heading
    boatdctl position
    boatdctl spin
    boatdctl rudder <angle>
    boatdctl sail <angle>

Options:
    -h --help     Show this screen.
    --version     Show boatd version

'''

import argparse

from boatdclient import Boat

if __name__ == '__main__':
    arger = argparse.ArgumentParser()
    subparsers = arger.add_subparsers(dest='command')

    info_parser = subparsers.add_parser('info')
    stop_parser = subparsers.add_parser('stop')
    heading_parser = subparsers.add_parser('heading')
    position_parser = subparsers.add_parser('position')
    spin_parser = subparsers.add_parser('spin')

    rudder_parser = subparsers.add_parser('rudder')
    rudder_parser.add_argument('angle')

    sail_parser = subparsers.add_parser('sail')
    sail_parser.add_argument('angle')

    opts = arger.parse_args()

    boat = Boat()

    if opts.command == 'rudder':
        print('setting rudder to', opts.angle)
        boat.rudder(float(opts.angle))

    if opts.command == 'sail':
        print('setting sail to', opts.angle)
        boat.sail(float(opts.angle))

    if opts.command == 'spin':
        import time
        for i in range(90):
            a = 45 - (i)
            boat.rudder(a)
